### ISSUE TITLE
Need some improvement:

### ISSUE THREAD

**Issue by TBTS-pvt-ltd-2011** [TBTS-pvt-ltd-2011/prototype_projects#7]
import sys
from tkinter import *
import time
 
def timing():
    current_time = time.strftime("%H : %M : %S")
    clock.config(text=current_time)
    #inserting a 200 seconds difference will output the exact time
    clock.after(200,timing)
 
root=Tk()
root.geometry("100x100")
clock=Label(root,font=("times",60,"bold"),bg="grey")
clock.grid(row=3,column=3,pady=20,padx=100)
timing()
 
digital=Label(root,font="arial")
digital.grid(row=2,column=2)
 
nota=Label(root,text="",font="arial")
nota.grid(row=3,column=2)
 
root.mainloop()

**Comment by pavans2011** [comment]
This is a very simple Wall clock portable code purely built with Python. I feel like this code needs some improvement, after a lot of testing and debugging, it feels incomplete. I factory reset-ed the HDL code previously present in the clock's motherboard and implemented this code by plugging it into the F-AC connector with the help of a 9.v/w B()-ry cell. But this clock project felt incomplete, it would be rewarding if anyone could work side-by-side with me to fix/improve this project.

**Comment by pavans2011** [comment]
This is a very simple Wall clock portable code purely built with Python. I feel like this code needs some improvement, after a lot of testing and debugging, it feels incomplete. I factory reset-ed the HDL code previously present in the clock's motherboard and implemented this code by plugging it into the F-AC connector with the help of a 9.v/w B()-ry cell. But this clock project felt incomplete, it would be rewarding if anyone could work side-by-side with me to fix/improve this project.
